// ============================================================
// Mythral - Tile types
// Single source of truth for tile definitions
// ============================================================

export const TILE = {
  DEEP_WATER: 0,
  WATER: 1,
  SAND: 2,
  GRASS: 3,
  DARK_GRASS: 4,
  FOREST: 5,
  DENSE_FOREST: 6,
  MOUNTAIN: 7,
  SNOW: 8,
  ICE: 9,
  LAVA: 10,
  VOLCANIC_ROCK: 11,
  SWAMP: 12,
  SWAMP_WATER: 13,
  DESERT: 14,
  DESERT_ROCK: 15,
  PATH: 16,
  WOOD_FLOOR: 17,
  STONE_FLOOR: 18,
  WALL: 19,
  DOOR: 20,
  BRIDGE: 21,
  CRYSTAL: 22,
  VOID: 23,
  CLOUD: 24,
  RUINS: 25,
  FLOWERS: 26,
  MUSHROOM: 27,
}

// sprite: original procedural-pixel-art key (generated by scripts/gen-assets.mjs)
export const TILE_INFO = {
  [TILE.DEEP_WATER]:    { name: 'Deep Water',  color: '#0c1e4a', walkable: false, decor: '🌊', sprite: 'tile.deepWater' },
  [TILE.WATER]:         { name: 'Water',        color: '#1e3a8a', walkable: false, decor: '≈', sprite: 'tile.water' },
  [TILE.SAND]:          { name: 'Sand',         color: '#fde68a', walkable: true, sprite: 'tile.sand' },
  [TILE.GRASS]:         { name: 'Grass',        color: '#4ade80', walkable: true, sprite: 'tile.grass' },
  [TILE.DARK_GRASS]:    { name: 'Tall Grass',   color: '#16a34a', walkable: true, sprite: 'tile.darkGrass' },
  [TILE.FOREST]:        { name: 'Forest',       color: '#15803d', walkable: true, decor: '🌲', sprite: 'tile.forest' },
  [TILE.DENSE_FOREST]:  { name: 'Dense Forest', color: '#14532d', walkable: false, decor: '🌲', sprite: 'tile.denseForest' },
  [TILE.MOUNTAIN]:      { name: 'Mountain',     color: '#57534e', walkable: false, decor: '▲', sprite: 'tile.mountain' },
  [TILE.SNOW]:          { name: 'Snow',         color: '#f1f5f9', walkable: true, sprite: 'tile.mountain' },
  [TILE.ICE]:           { name: 'Ice',          color: '#bae6fd', walkable: true, decor: '❄', sprite: 'tile.water' },
  [TILE.LAVA]:          { name: 'Lava',         color: '#dc2626', walkable: false, decor: '🔥', sprite: 'tile.deepWater' },
  [TILE.VOLCANIC_ROCK]: { name: 'Volcanic Rock',color: '#451a03', walkable: true, sprite: 'tile.grass' },
  [TILE.SWAMP]:         { name: 'Swamp',        color: '#3f6212', walkable: true, decor: '🌿', sprite: 'tile.darkGrass' },
  [TILE.SWAMP_WATER]:   { name: 'Murky Water',  color: '#365314', walkable: false, decor: '≈', sprite: 'tile.water' },
  [TILE.DESERT]:        { name: 'Desert',       color: '#fbbf24', walkable: true, sprite: 'tile.sand' },
  [TILE.DESERT_ROCK]:   { name: 'Desert Rock',  color: '#a16207', walkable: false, decor: '▲', sprite: 'tile.mountain' },
  [TILE.PATH]:          { name: 'Path',         color: '#a8a29e', walkable: true, monsterSafe: false, sprite: 'tile.path' },
  [TILE.WOOD_FLOOR]:    { name: 'Wood Floor',   color: '#92400e', walkable: true, monsterSafe: false, sprite: 'tile.woodFloor' },
  [TILE.STONE_FLOOR]:   { name: 'Stone Floor',  color: '#71717a', walkable: true, monsterSafe: false, sprite: 'tile.stoneFloor' },
  [TILE.WALL]:          { name: 'Wall',         color: '#27272a', walkable: false, decor: '🧱', sprite: 'tile.wall' },
  [TILE.DOOR]:          { name: 'Door',         color: '#92400e', walkable: true, monsterSafe: false, decor: '🚪', sprite: 'tile.door' },
  [TILE.BRIDGE]:        { name: 'Bridge',       color: '#78350f', walkable: true, sprite: 'tile.bridge' },
  [TILE.CRYSTAL]:       { name: 'Crystal',      color: '#a78bfa', walkable: false, decor: '💎', sprite: 'tile.mountain' },
  [TILE.VOID]:          { name: 'Void',         color: '#1e1b4b', walkable: true, decor: '✦', sprite: 'tile.darkGrass' },
  [TILE.CLOUD]:         { name: 'Cloud',        color: '#f1f5f9', walkable: true, decor: '☁', sprite: 'tile.grass' },
  [TILE.RUINS]:         { name: 'Ruins',        color: '#78716c', walkable: true, decor: '🏛', sprite: 'tile.ruins' },
  [TILE.FLOWERS]:       { name: 'Flowers',      color: '#f472b6', walkable: true, decor: '🌸', sprite: 'tile.flowers' },
  [TILE.MUSHROOM]:      { name: 'Mushrooms',    color: '#9333ea', walkable: true, decor: '🍄', sprite: 'tile.mushroom' },
}

// variation count per sprite base (must match gen-tiles TILE_VARIATIONS)
export const TILE_VARIATION_COUNT = {
  'tile.grass': 4, 'tile.darkGrass': 4, 'tile.flowers': 1, 'tile.sand': 3,
  'tile.path': 3, 'tile.water': 3, 'tile.deepWater': 3, 'tile.woodFloor': 2,
  'tile.stoneFloor': 2, 'tile.wall': 2, 'tile.door': 1, 'tile.bridge': 1,
  'tile.ruins': 2, 'tile.mushroom': 1, 'tile.forest': 1, 'tile.denseForest': 1,
  'tile.mountain': 1,
}

export function isWalkable(tile) {
  const info = TILE_INFO[tile]
  return info ? info.walkable : false
}

// Helper: build a rectangular island with water border
export function makeIsland(width, height, baseTile, fillFn) {
  const map = []
  for (let y = 0; y < height; y++) {
    const row = []
    for (let x = 0; x < width; x++) {
      row.push(fillFn(x, y, width, height))
    }
    map.push(row)
  }
  return map
}

// Helper: stamp a rectangle of tiles onto the map
export function stampRect(map, x, y, w, h, tile) {
  for (let dy = 0; dy < h; dy++) {
    for (let dx = 0; dx < w; dx++) {
      const tx = x + dx, ty = y + dy
      if (ty >= 0 && ty < map.length && tx >= 0 && tx < map[0].length) {
        map[ty][tx] = tile
      }
    }
  }
}

// Helper: stamp a building (walls + wood floor + door)
export function stampBuilding(map, x, y, w, h, floorTile = TILE.WOOD_FLOOR, wallTile = TILE.WALL, doorOnBottom = true) {
  // perimeter walls
  for (let dx = 0; dx < w; dx++) {
    if (y >= 0 && y < map.length && x + dx >= 0 && x + dx < map[0].length) map[y][x + dx] = wallTile
    if (y + h - 1 >= 0 && y + h - 1 < map.length && x + dx >= 0 && x + dx < map[0].length) map[y + h - 1][x + dx] = wallTile
  }
  for (let dy = 0; dy < h; dy++) {
    if (x >= 0 && x < map[0].length && y + dy >= 0 && y + dy < map.length) map[y + dy][x] = wallTile
    if (x + w - 1 >= 0 && x + w - 1 < map[0].length && y + dy >= 0 && y + dy < map.length) map[y + dy][x + w - 1] = wallTile
  }
  // interior floor
  stampRect(map, x + 1, y + 1, w - 2, h - 2, floorTile)
  // door
  if (doorOnBottom) {
    const doorX = x + Math.floor(w / 2)
    if (y + h - 1 < map.length && doorX < map[0].length) map[y + h - 1][doorX] = TILE.DOOR
  } else {
    const doorX = x + Math.floor(w / 2)
    if (y >= 0 && doorX < map[0].length) map[y][doorX] = TILE.DOOR
  }
}
